### ISSUE TITLE
Create new site

### ISSUE THREAD

**Issue by brettfarley** [brettfarley/Reese#1]
Find theme to copy this site: http://www.gtbynum.com

**Comment by supportast** [comment]
Work in progress. I will create a sub domain and put it on live tomorrow . Please let me know if inner pages are also required to be made .

**Comment by brettfarley** [comment]
Thanks. please make the sub domain reese.vsstaging.net. On inner pages,
this is a one-page site similar to the Pugh site so no need for inner pages.

**Comment by supportast** [comment]
Work in progress on reese.vsstaging.net.

**Comment by supportast** [comment]
Please provide the content for the site .

**Comment by brettfarley** [comment]
Please just copy content from the example site. We will edit later.

**Comment by supportast** [comment]
Done ..Except Twitter slider . For this either I can make a slider from which twitter feeds will be added from added .like in reference site ..is this fine .

**Comment by brettfarley** [comment]
That's fine, so long as it looks the same.

**Comment by supportast** [comment]
Done .please check

**Comment by supportast** [comment]
username: brettafarley
Password: Forjesus4
